using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using xdef.net.Connection;
using xdef.net.Connection.Library;
using xdef.net.Sys;
using xdef.net.Utils;

namespace xdef.net
{
    public sealed class XDDocument : RemoteObject
    {
        private const int FUNCTION_SETPROPERTIES = 1;
        private const int FUNCTION_SETPROPERTY = 2;
        private const int FUNCTION_GETPROPERTIES = 3;
        private const int FUNCTION_ISCREATEMODE = 4;
        private const int FUNCTION_GETDOCUMENT = 5;
        private const int FUNCTION_SETROOTMODEL = 6;
        private const int FUNCTION_XPARSE_1 = 7;
        private const int FUNCTION_XPARSE_2 = 8;
        private const int FUNCTION_XPARSE_3 = 9;
        private const int FUNCTION_XPARSE_4 = 10;
        private const int FUNCTION_XPARSE_5 = 11;
        private const int FUNCTION_XPARSE_6 = 12;
        private const int FUNCTION_XPARSE_7 = 13;
        private const int FUNCTION_XCREATE_1 = 14;
        private const int FUNCTION_XCREATE_2 = 15;
        private const int FUNCTION_XCREATE_3 = 16;
        private const int FUNCTION_PARSEXCOMPONENT_1 = 17;
        private const int FUNCTION_PARSEXCOMPONENT_2 = 18;
        private const int FUNCTION_PARSEXCOMPONENT_3 = 19;
        private const int FUNCTION_PARSEXCOMPONENT_4 = 20;
        private const int FUNCTION_PARSEXCOMPONENT_5 = 21;
        private const int FUNCTION_PARSEXCOMPONENT_6 = 22;
        private const int FUNCTION_JPARSE_1 = 23;
        private const int FUNCTION_JPARSE_2 = 24;
        private const int FUNCTION_JPARSE_3 = 25;
        private const int FUNCTION_JPARSE_4 = 26;
        private const int FUNCTION_JPARSE_5 = 27;
        private const int FUNCTION_JPARSE_6 = 28;
        private const int FUNCTION_JPARSEXCOMPONENT_1 = 29;
        private const int FUNCTION_JPARSEXCOMPONENT_2 = 30;
        private const int FUNCTION_JPARSEXCOMPONENT_3 = 31;
        private const int FUNCTION_JPARSEXCOMPONENT_4 = 32;
        private const int FUNCTION_JPARSEXCOMPONENT_5 = 33;
        private const int FUNCTION_JPARSEXCOMPONENT_6 = 34;
        private const int FUNCTION_GETSTDOUT = 35;
        private const int FUNCTION_GETSTDERR = 36;
        private const int FUNCTION_GETSTDIN = 37;
        private const int FUNCTION_SETSTREAMWRITER_1 = 38;
        private const int FUNCTION_SETSTREAMWRITER_2 = 39;
        private const int FUNCTION_SETSTREAMWRITER_3 = 40;
        private const int FUNCTION_SETSTDOUT_1 = 41;
        private const int FUNCTION_SETSTDOUT_2 = 42;
        private const int FUNCTION_SETSTDIN_1 = 43;
        private const int FUNCTION_SETSTDOUT_3 = 44;
        private const int FUNCTION_SETSTDIN_2 = 45;
        private const int FUNCTION_SETDEBUGGER = 46;
        private const int FUNCTION_GETDEBUGGER = 47;
        private const int FUNCTION_SETDEBUG = 48;
        private const int FUNCTION_ISDEBUG = 49;
        private const int FUNCTION_PREPAREROOTXXELEMENTNS = 50;
        private const int FUNCTION_PREPAREROOTXXELEMENT = 51;
        private const int FUNCTION_GETIMPLPROPERTIES = 52;
        private const int FUNCTION_GETIMPLPROPERTY = 53;
        private const int FUNCTION_ISLEGALDATE = 54;
        private const int FUNCTION_GETMINYEAR = 55;
        private const int FUNCTION_SETMINYEAR = 56;
        private const int FUNCTION_GETMAXYEAR = 57;
        private const int FUNCTION_SETMAXYEAR = 58;
        private const int FUNCTION_GETSPECIALDATES = 59;
        private const int FUNCTION_SETSPECIALDATES = 60;
        private const int FUNCTION_CHECKDATELEGAL = 61;
        private const int FUNCTION_PRINTREPORTS = 62;
        private const int FUNCTION_GETLEXICONLANGUAGE = 63;
        private const int FUNCTION_SETLEXICONLANGUAGE = 64;
        private const int FUNCTION_XTRANSLATE_1 = 65;
        private const int FUNCTION_XTRANSLATE_2 = 66;

        internal XDDocument(int objectId, Client client) : base(objectId, client)
        {
        }

        // Autogenerated method
        //  public abstract void setProperties(java.util.Properties);
        public void SetProperties(Utils.Properties arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETPROPERTIES, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setProperty(java.lang.String, java.lang.String);
        public void SetProperty(String arg0, String arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETPROPERTY, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract java.util.Properties getProperties();
        public Utils.Properties GetProperties()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETPROPERTIES, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return Utils.Properties.Deserialize(reader);
                }
            }
        }

        // Autogenerated method
        //  public abstract boolean isCreateMode();
        public bool IsCreateMode()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_ISCREATEMODE, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadBoolean();
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Document getDocument();
        public XDocument GetDocument()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETDOCUMENT, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return XDocument.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract void setRootModel(org.xdef.model.XMElement);
        /*
        public void SetRootModel(XMElement arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETROOTMODEL, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }*/

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(String arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.lang.String, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(String arg0, String arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.net.URL, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(Uri arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.io.File, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(FilePath arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_4, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(org.w3c.dom.Node, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(XNode arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_5, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.io.InputStream, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(Stream arg0, ReportWriter arg1)
        {
            if (!arg0.CanRead) throw new ArgumentException("Stream no readable");
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(_client.RegisterLocalObject(new RemoteStreamWrapper(_client, arg0)));
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_6, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xparse(java.io.InputStream, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xparse(Stream arg0, String arg1, ReportWriter arg2)
        {
            if (!arg0.CanRead) throw new ArgumentException("Stream no readable");
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(_client.RegisterLocalObject(new RemoteStreamWrapper(_client, arg0)));
                builder.Add(arg1);
                builder.Add(arg2.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XPARSE_7, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xcreate(java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xcreate(String arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XCREATE_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xcreate(java.lang.String, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xcreate(String arg0, String arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XCREATE_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xcreate(javax.xml.namespace.QName, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xcreate(XmlQualifiedName arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XCREATE_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(java.lang.String, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        /*
        public XComponent ParseXComponent(String arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(java.io.File, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent ParseXComponent(File arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(java.net.URL, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent ParseXComponent(URL arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(java.io.InputStream, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent ParseXComponent(InputStream arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_4, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(java.io.InputStream, java.lang.Class<?>, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent ParseXComponent(InputStream arg0, Class<?> arg1, String arg2, ReportWriter arg3)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                builder.Add(arg3);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_5, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent parseXComponent(org.w3c.dom.Node, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent ParseXComponent(Node arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PARSEXCOMPONENT_6, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(String arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(java.io.File, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(File arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(java.net.URL, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(URL arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(java.io.InputStream, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(InputStream arg0, String arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_4, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(org.w3c.dom.Node, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(Node arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_5, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.Object jparse(java.lang.Object, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public Object Jparse(Object arg0, ReportWriter arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSE_6, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new Object(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(java.lang.String, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(String arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(java.net.URL, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(URL arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(java.io.InputStream, java.lang.String, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(InputStream arg0, String arg1, Class<?> arg2, ReportWriter arg3)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                builder.Add(arg3);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(java.io.File, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(File arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_4, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(org.w3c.dom.Node, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(Node arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_5, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.component.XComponent jparseXComponent(java.lang.Object, java.lang.Class<?>, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XComponent JparseXComponent(Object arg0, Class<?> arg1, ReportWriter arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_JPARSEXCOMPONENT_6, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XComponent(reader.ReadInt32(), _client);
                }
            }
        } */

        // Autogenerated method
        //  public abstract org.xdef.XDOutput getStdOut();
        public XDOutput GetStdOut()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETSTDOUT, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XDOutput(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.XDOutput getStdErr();
        public XDOutput GetStdErr()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETSTDERR, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XDOutput(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.XDInput getStdIn();
        public XDInput GetStdIn()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETSTDIN, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XDInput(reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStreamWriter(java.io.OutputStream, java.lang.String, boolean) throws java.io.IOException;

        public void SetStreamWriter(Stream arg0, String arg1, bool arg2)
        {
            if (!arg0.CanWrite) throw new ArgumentException("Stream not writable");
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(_client.RegisterLocalObject(new RemoteStreamWrapper(_client, arg0)));
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTREAMWRITER_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }
        /*
        // Autogenerated method
        //  public abstract void setStreamWriter(java.io.Writer, java.lang.String, boolean);
        public void SetStreamWriter(Writer arg0, String arg1, boolean arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTREAMWRITER_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStreamWriter(org.xdef.XDXmlOutStream);
        public void SetStreamWriter(XDXmlOutStream arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTREAMWRITER_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStdOut(java.io.PrintStream);

        public void SetStdOut(PrintStream arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTDOUT_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStdOut(java.io.Writer);
        public void SetStdOut(Writer arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTDOUT_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }*/

        // Autogenerated method
        //  public abstract void setStdIn(java.io.InputStream);
        public void SetStdIn(Stream arg0)
        {
            if (!arg0.CanRead) throw new ArgumentException("Stream no readable");
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(_client.RegisterLocalObject(new RemoteStreamWrapper(_client, arg0)));
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTDIN_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStdOut(org.xdef.XDOutput);
        public void SetStdOut(XDOutput arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTDOUT_3, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void setStdIn(org.xdef.XDInput);
        public void SetStdIn(XDInput arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSTDIN_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }
        /*
        // Autogenerated method
        //  public abstract void setDebugger(org.xdef.XDDebug);
        public void SetDebugger(XDDebug arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETDEBUGGER, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.XDDebug getDebugger();
        public XDDebug GetDebugger()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETDEBUGGER, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XDDebug(reader.ReadInt32(), _client);
                }
            }
        }*/

        // Autogenerated method
        //  public abstract void setDebug(boolean);
        public void SetDebug(bool arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETDEBUG, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract boolean isDebug();
        public bool IsDebug()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_ISDEBUG, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadBoolean();
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.proc.XXElement prepareRootXXElementNS(java.lang.String, java.lang.String, boolean);
        /*
        public XXElement PrepareRootXXElementNS(String arg0, String arg1, bool arg2)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                var res = SendRequestWithResponse(new Request(FUNCTION_PREPAREROOTXXELEMENTNS, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XXElement(reader.ReadInt32(), _client);
                }
            }
        }*/

        // Autogenerated method
        //  public abstract org.xdef.proc.XXElement prepareRootXXElement(java.lang.String, boolean);
        /*
        public XXElement PrepareRootXXElement(String arg0, boolean arg1)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                var res = SendRequestWithResponse(new Request(FUNCTION_PREPAREROOTXXELEMENT, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new XXElement(reader.ReadInt32(), _client);
                }
            }
        }*/

        // Autogenerated method
        //  public abstract java.util.Properties getImplProperties();

        public Utils.Properties GetImplProperties()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETIMPLPROPERTIES, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return Utils.Properties.Deserialize(reader);
                }
            }
        }

        // Autogenerated method
        //  public abstract java.lang.String getImplProperty(java.lang.String);
        public String GetImplProperty(String arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_GETIMPLPROPERTY, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadString();
                }
            }
        }

        // Autogenerated method
        //  public abstract boolean isLegalDate(org.xdef.sys.SDatetime);
        /*
        public bool IsLegalDate(SDatetime arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_ISLEGALDATE, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadBoolean();
                }
            }
        }*/

        // Autogenerated method
        //  public abstract int getMinYear();
        public int GetMinYear()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETMINYEAR, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadInt32();
                }
            }
        }

        // Autogenerated method
        //  public abstract void setMinYear(int);
        public void SetMinYear(int arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETMINYEAR, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract int getMaxYear();
        public int GetMaxYear()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETMAXYEAR, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadInt32();
                }
            }
        }

        // Autogenerated method
        //  public abstract void setMaxYear(int);
        public void SetMaxYear(int arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETMAXYEAR, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract org.xdef.sys.SDatetime[] getSpecialDates();
        /*
        public SDatetime[] GetSpecialDates()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETSPECIALDATES, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    // Read response here
                    return new SDatetime[](reader.ReadInt32(), _client);
                }
            }
        }

        // Autogenerated method
        //  public abstract void setSpecialDates(org.xdef.sys.SDatetime[]);
        public void SetSpecialDates(SDatetime[] arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETSPECIALDATES, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }*/

        // Autogenerated method
        //  public abstract void checkDateLegal(boolean);
        public void CheckDateLegal(bool arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_CHECKDATELEGAL, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract void printReports(java.io.PrintStream);
        /*
        public void PrintReports(PrintStream arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_PRINTREPORTS, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }*/

        // Autogenerated method
        //  public abstract java.lang.String getLexiconLanguage();
        public String GetLexiconLanguage()
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                var res = SendRequestWithResponse(new Request(FUNCTION_GETLEXICONLANGUAGE, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return reader.ReadString();
                }
            }
        }

        // Autogenerated method
        //  public abstract void setLexiconLanguage(java.lang.String) throws org.xdef.sys.SRuntimeException;
        public void SetLexiconLanguage(String arg0)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                var res = SendRequestWithResponse(new Request(FUNCTION_SETLEXICONLANGUAGE, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return;
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xtranslate(java.lang.String, java.lang.String, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xtranslate(String arg0, String arg1, String arg2, ReportWriter arg3)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                builder.Add(arg3.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XTRANSLATE_1, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

        // Autogenerated method
        //  public abstract org.w3c.dom.Element xtranslate(org.w3c.dom.Element, java.lang.String, java.lang.String, org.xdef.sys.ReportWriter) throws org.xdef.sys.SRuntimeException;
        public XElement Xtranslate(XElement arg0, String arg1, String arg2, ReportWriter arg3)
        {
            using (var builder = new BigEndianDataBuilder())
            {
                // Serialize args here
                builder.Add(arg0);
                builder.Add(arg1);
                builder.Add(arg2);
                builder.Add(arg3.ObjectId);
                var res = SendRequestWithResponse(new Request(FUNCTION_XTRANSLATE_2, builder.Build(), ObjectId));
                using (var reader = res.Reader)
                {
                    return XElement.Parse(reader.ReadString());
                }
            }
        }

    }
}
